version: "2.2"
services:
  jd-seckill:
    container_name: jd-seckill
    image: tumi/jd-seckill:latest
    build:
      context: ../dockerfile
      dockerfile: Dockerfile
    env_file:
      - ../dockerfile/.env
